#!/bin/bash

# Extract details from data.json
name=$(./jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(./jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
height=$(./jq -r '.height' data.json)
weight=$(./jq -r '.weight' data.json)

# Convert to readable units
formatted_height=$(awk "BEGIN {printf \"%.1f\", $height / 10}")
formatted_weight=$(awk "BEGIN {printf \"%.1f\", $weight / 10}")

# Final formatted sentence
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
